Repository zipkimi/back-zipkimi, pull requests merged in 2023-09, with the labels that each got.

#25 Feature/#21 일반회원 가입 api 추가
  build.gradle
  src/main/java/com/zipkimi/entity/UserEntity.java
  src/main/java/com/zipkimi/global/config/SecurityConfig.java
  src/main/java/com/zipkimi/global/controller/TestController.java
  src/main/java/com/zipkimi/global/interceptor/LogInterceptor.java
  src/main/java/com/zipkimi/global/utils/RegexUtils.java
  src/main/java/com/zipkimi/repository/SmsAuthRepository.java
  src/main/java/com/zipkimi/repository/UserRepository.java
  src/main/java/com/zipkimi/user/controller/UserLoginController.java
  src/main/java/com/zipkimi/user/controller/UserManagementController.java
  src/main/java/com/zipkimi/user/dto/request/JoinUserPostRequest.java
  src/main/java/com/zipkimi/user/dto/request/SmsAuthNumberGetRequest.java
  src/main/java/com/zipkimi/user/dto/response/JoinUserPostResponse.java
  src/main/java/com/zipkimi/user/dto/response/SmsAuthNumberGetResponse.java
  src/main/java/com/zipkimi/user/dto/response/SmsAuthNumberPostResponse.java
  src/main/java/com/zipkimi/user/service/UserManagementService.java
  src/test/java/com/zipkimi/user/controller/UserLoginControllerTest.java
  src/test/java/com/zipkimi/user/controller/UserManagementControllerTest.java
  src/test/java/com/zipkimi/user/service/UserLoginServiceTest.java
  src/test/java/com/zipkimi/user/service/UserManagementServiceTest.java
Labels: 💫 feature

#28 Feature/#27-SpirngSecurity-Jwt-로그인-API
  build.gradle
  src/main/java/com/zipkimi/entity/UserEntity.java
  src/main/java/com/zipkimi/entity/UserRole.java
  src/main/java/com/zipkimi/global/config/SecurityConfig.java
  src/main/java/com/zipkimi/global/jwt/JwtTokenProvider.java
  src/main/java/com/zipkimi/global/jwt/config/CustomAccessDeniedHandler.java
  src/main/java/com/zipkimi/global/jwt/controller/TokenExceptionController.java
  src/main/java/com/zipkimi/global/jwt/dto/request/TokenRequest.java
  src/main/java/com/zipkimi/global/jwt/dto/response/TokenResponse.java
  src/main/java/com/zipkimi/global/jwt/entity/RefreshTokenEntity.java
  src/main/java/com/zipkimi/global/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/zipkimi/global/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/zipkimi/global/security/CustomUserDetailsService.java
  src/main/java/com/zipkimi/global/security/exception/CustomAuthenticationEntryPointException.java
  src/main/java/com/zipkimi/repository/UserRepository.java
  src/main/java/com/zipkimi/user/controller/UserLoginController.java
  src/main/java/com/zipkimi/user/dto/request/UserLoginRequest.java
  src/main/java/com/zipkimi/user/dto/response/FindSmsAuthNumberGetResponse.java
  src/main/java/com/zipkimi/user/service/UserLoginService.java
  src/main/resources/application-prod.properties
Labels: ♻️ refactor, 💫 feature, ⚙️ chore

#45 Feat : 시공사 회원 관련 클래스 생성
  src/main/java/com/zipkimi/entity/BuilderUserEntity.java
  src/main/java/com/zipkimi/repository/BuilderUserRepository.java
Labels: 💫 feature

#47 Refactor : 시공사 관련 도메인 엔티티 수정/추가 및 CommonUtils 생성
  src/main/java/com/zipkimi/builder/controller/BuilderManagementController.java
  src/main/java/com/zipkimi/builder/service/BuilderManagementService.java
  src/main/java/com/zipkimi/entity/BuilderEntity.java
  src/main/java/com/zipkimi/entity/BuilderUserEntity.java
  src/main/java/com/zipkimi/global/config/SecurityConfig.java
  src/main/java/com/zipkimi/global/utils/CodeConstant.java
  src/main/java/com/zipkimi/global/utils/CommonUtils.java
  src/main/java/com/zipkimi/repository/BuilderUserRepository.java
  src/main/java/com/zipkimi/user/service/UserLoginService.java
Labels: ♻️ refactor
